/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar sesión
         * @description Retorna un access token (JWT, 1h) y un refresh token (30d).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "email": "maria.docente@colegio.edu.ar",
                     *       "password": "MiPassword123"
                     *     }
                     */
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Login exitoso */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                         *       "refreshToken": "dGhpcyBpcyBhIHJlZnJlc2ggdG9rZW4...",
                         *       "user": {
                         *         "id": "usr_01HXZ",
                         *         "email": "maria.docente@colegio.edu.ar",
                         *         "role": "docente",
                         *         "displayName": "María Pérez"
                         *       }
                         *     }
                         */
                        "application/json": components["schemas"]["AuthTokens"];
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cerrar sesión
         * @description Invalida el refresh token del usuario.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "refreshToken": "dGhpcyBpcyBhIHJlZnJlc2ggdG9rZW4..."
                     *     }
                     */
                    "application/json": {
                        refreshToken?: string;
                    };
                };
            };
            responses: {
                /** @description Sesión cerrada */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Renovar access token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "refreshToken": "dGhpcyBpcyBhIHJlZnJlc2ggdG9rZW4..."
                     *     }
                     */
                    "application/json": {
                        refreshToken?: string;
                    };
                };
            };
            responses: {
                /** @description Nuevo access token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.NEW..."
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/forgot-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Solicitar recuperación de contraseña */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "email": "padre@gmail.com"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Email de recuperación enviado (siempre 200 para evitar enumeración) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resetear contraseña con token */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "token": "a1b2c3d4e5f6...",
                     *       "newPassword": "NuevaPassword456"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Contraseña actualizada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Token inválido o expirado */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perfil del usuario autenticado */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Datos del usuario */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": "usr_01HXZ",
                         *       "email": "maria.docente@colegio.edu.ar",
                         *       "role": "docente",
                         *       "displayName": "María Pérez",
                         *       "googleAccountId": "117890123456789012345",
                         *       "createdAt": "2024-03-01T10:00:00Z"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/prospects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar prospectos
         * @description Solo accesible para directores y admins.
         */
        get: {
            parameters: {
                query?: {
                    /** @example aceptado */
                    status?: "pendiente" | "entrevistado" | "aceptado" | "rechazado" | "alta";
                    /** @example 2do primaria */
                    grade?: string;
                    /** @example 2025-01-01 */
                    from?: string;
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista paginada de prospectos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "id": "pros_08ABX",
                         *           "studentName": "Lucas Rodríguez",
                         *           "gradeApplying": "2do primaria",
                         *           "status": "aceptado",
                         *           "parentEmail": "carlos.rodriguez@gmail.com",
                         *           "createdAt": "2025-04-09T14:22:00Z"
                         *         },
                         *         {
                         *           "id": "pros_09CDE",
                         *           "studentName": "Valentina López",
                         *           "gradeApplying": "3er primaria",
                         *           "status": "entrevistado",
                         *           "parentEmail": "ana.lopez@outlook.com",
                         *           "createdAt": "2025-04-08T09:10:00Z"
                         *         }
                         *       ],
                         *       "pagination": {
                         *         "page": 1,
                         *         "limit": 20,
                         *         "total": 47
                         *       }
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        /**
         * Registrar nuevo prospecto (formulario web)
         * @description Endpoint público. Recibe los datos del formulario de admisión y los persiste en la DB con estado `pendiente`.
         *     No crea cuenta en Google Workspace todavía.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "studentName": "Lucas Rodríguez",
                     *       "birthDate": "2015-06-14",
                     *       "gradeApplying": "2do primaria",
                     *       "parentName": "Carlos Rodríguez",
                     *       "parentEmail": "carlos.rodriguez@gmail.com",
                     *       "parentPhone": "+54 11 5555-1234",
                     *       "notes": "El alumno tiene experiencia en colegio bilingüe"
                     *     }
                     */
                    "application/json": components["schemas"]["ProspectCreate"];
                };
            };
            responses: {
                /** @description Prospecto registrado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": "pros_08ABX",
                         *       "status": "pendiente",
                         *       "createdAt": "2025-04-09T14:22:00Z"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
                422: components["responses"]["ValidationError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/prospects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Detalle de un prospecto */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example usr_0ZLUQ */
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prospecto encontrado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": "pros_08ABX",
                         *       "studentName": "Lucas Rodríguez",
                         *       "birthDate": "2015-06-14",
                         *       "gradeApplying": "2do primaria",
                         *       "status": "aceptado",
                         *       "parentName": "Carlos Rodríguez",
                         *       "parentEmail": "carlos.rodriguez@gmail.com",
                         *       "parentPhone": "+54 11 5555-1234",
                         *       "notes": "El alumno tiene experiencia en colegio bilingüe",
                         *       "history": [
                         *         {
                         *           "status": "pendiente",
                         *           "changedAt": "2025-04-09T14:22:00Z",
                         *           "changedBy": null
                         *         },
                         *         {
                         *           "status": "entrevistado",
                         *           "changedAt": "2025-04-10T11:00:00Z",
                         *           "changedBy": "usr_ADMIN1"
                         *         },
                         *         {
                         *           "status": "aceptado",
                         *           "changedAt": "2025-04-11T09:30:00Z",
                         *           "changedBy": "usr_ADMIN1"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/prospects/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar estado del prospecto */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example usr_0ZLUQ */
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "status": "entrevistado",
                     *       "comment": "Entrevista realizada el 10/04. Familia interesada."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Estado actualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": "pros_08ABX",
                         *       "status": "entrevistado",
                         *       "updatedAt": "2025-04-10T11:00:00Z"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        trace?: never;
    };
    "/admissions/prospects/{id}/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dar de alta a un prospecto aceptado
         * @description Flujo completo de alta:
         *     1. Valida que el prospecto tenga estado `aceptado`
         *     2. Crea el usuario en la DB interna con rol `alumno`
         *     3. Llama a Google Workspace (`POST /admin/directory/v1/users`) para crear cuenta institucional
         *     4. Llama a Google Classroom (`POST /v1/courses/{courseId}/students`) para inscribir al alumno
         *     5. Actualiza el estado del prospecto a `alta`
         *
         *     En caso de fallo parcial (ej: Workspace OK pero Classroom falla), el job queda en cola para reintento.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example usr_0ZLUQ */
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "courseId": "course_5B_2025",
                     *       "classroomCourseId": "123456789",
                     *       "institutionalEmail": "lucas.rodriguez@colegio.edu.ar"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Alta realizada exitosamente */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "userId": "usr_0ZLUQ",
                         *       "institutionalEmail": "lucas.rodriguez@colegio.edu.ar",
                         *       "googleAccountId": "108765432109876543210",
                         *       "classroomEnrolled": true,
                         *       "prospectStatus": "alta"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
                /** @description El prospecto no está en estado `aceptado` */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Error al comunicarse con Google APIs (ver campo `failedStep`) */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "error": "GOOGLE_WORKSPACE_ERROR",
                         *       "failedStep": "workspace_user_create",
                         *       "message": "La cuenta ya existe en Google Workspace"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar postulaciones laborales */
        get: {
            parameters: {
                query?: {
                    /** @example Docente de Matemática */
                    position?: string;
                    status?: "recibida" | "en_revision" | "entrevistado" | "contratado" | "descartado";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de postulaciones */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "id": "job_APP_022",
                         *           "applicantName": "Jorge Fernández",
                         *           "position": "Docente de Matemática",
                         *           "status": "en_revision",
                         *           "email": "jorge.fernandez@gmail.com",
                         *           "createdAt": "2025-04-09T15:00:00Z"
                         *         }
                         *       ],
                         *       "pagination": {
                         *         "page": 1,
                         *         "total": 12
                         *       }
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        /**
         * Postulación laboral
         * @description Público. No crea acceso al campus ni cuenta institucional.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "position": "Docente de Matemática",
                     *       "applicantName": "Jorge Fernández",
                     *       "email": "jorge.fernandez@gmail.com",
                     *       "phone": "+54 9 351 444-5678",
                     *       "cvUrl": "https://drive.google.com/file/d/1abc...",
                     *       "coverLetter": "Me postulo para el cargo porque..."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Postulación recibida */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": "job_APP_022",
                         *       "status": "recibida",
                         *       "createdAt": "2025-04-09T15:00:00Z"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admissions/jobs/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar estado de postulación laboral */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example usr_0ZLUQ */
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "status": "entrevistado",
                     *       "comment": "Entrevista agendada para el 15/04"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Estado actualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar alumnos */
        get: {
            parameters: {
                query?: {
                    /** @example course_5B_2025 */
                    courseId?: string;
                    /** @example 2025 */
                    year?: number;
                    /** @example Rodriguez */
                    search?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de alumnos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "id": "usr_0ZLUQ",
                         *           "displayName": "Lucas Rodríguez",
                         *           "institutionalEmail": "lucas.rodriguez@colegio.edu.ar",
                         *           "courseId": "course_5B_2025",
                         *           "courseName": "5to B",
                         *           "googleAccountId": "108765432109876543210"
                         *         },
                         *         {
                         *           "id": "usr_0ABCD",
                         *           "displayName": "Valentina López",
                         *           "institutionalEmail": "valentina.lopez@colegio.edu.ar",
                         *           "courseId": "course_5B_2025",
                         *           "courseName": "5to B",
                         *           "googleAccountId": "107654321098765432109"
                         *         }
                         *       ],
                         *       "pagination": {
                         *         "page": 1,
                         *         "total": 28
                         *       }
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perfil completo del alumno */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example usr_0ZLUQ */
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Perfil del alumno */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": "usr_0ZLUQ",
                         *       "displayName": "Lucas Rodríguez",
                         *       "birthDate": "2015-06-14",
                         *       "institutionalEmail": "lucas.rodriguez@colegio.edu.ar",
                         *       "googleAccountId": "108765432109876543210",
                         *       "courseId": "course_5B_2025",
                         *       "courseName": "5to B",
                         *       "parents": [
                         *         {
                         *           "name": "Carlos Rodríguez",
                         *           "email": "carlos.rodriguez@gmail.com",
                         *           "phone": "+54 11 5555-1234"
                         *         }
                         *       ],
                         *       "enrolledAt": "2025-03-01T00:00:00Z"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{id}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard del alumno
         * @description Combina datos de Google Classroom (tareas, exámenes, calificaciones)
         *     con datos internos (asistencia). Los exámenes se identifican porque el
         *     título contiene la palabra `[EXAMEN]`.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example usr_0ZLUQ */
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Vista consolidada del alumno */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "student": {
                         *         "id": "usr_0ZLUQ",
                         *         "displayName": "Lucas Rodríguez",
                         *         "courseName": "5to B"
                         *       },
                         *       "upcomingWork": [
                         *         {
                         *           "id": "cw_111",
                         *           "title": "[EXAMEN] Fracciones - Matemática",
                         *           "type": "exam",
                         *           "dueDate": "2025-04-15T08:00:00Z",
                         *           "subject": "Matemática",
                         *           "status": "pendiente"
                         *         },
                         *         {
                         *           "id": "cw_222",
                         *           "title": "Ejercicios de redacción - Lengua",
                         *           "type": "task",
                         *           "dueDate": "2025-04-12T23:59:00Z",
                         *           "subject": "Lengua",
                         *           "status": "entregado"
                         *         }
                         *       ],
                         *       "recentGrades": [
                         *         {
                         *           "subject": "Matemática",
                         *           "assignmentTitle": "Multiplicación de decimales",
                         *           "grade": 8.5,
                         *           "maxGrade": 10,
                         *           "gradedAt": "2025-04-05T00:00:00Z"
                         *         }
                         *       ],
                         *       "attendance": {
                         *         "totalDays": 60,
                         *         "presentDays": 57,
                         *         "absentDays": 3,
                         *         "percentage": 95
                         *       }
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar cursos */
        get: {
            parameters: {
                query?: {
                    /** @example 2025 */
                    year?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Lista de cursos */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "id": "course_5B_2025",
                         *           "name": "5to B",
                         *           "year": 2025,
                         *           "classroomCourseId": "123456789",
                         *           "teacherId": "usr_TEACH1",
                         *           "teacherName": "María Pérez",
                         *           "studentCount": 28
                         *         },
                         *         {
                         *           "id": "course_6A_2025",
                         *           "name": "6to A",
                         *           "year": 2025,
                         *           "classroomCourseId": "987654321",
                         *           "teacherId": "usr_TEACH2",
                         *           "teacherName": "Roberto García",
                         *           "studentCount": 25
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        /**
         * Crear curso
         * @description Crea el curso en la DB interna y llama a `POST /v1/courses` en Google Classroom.
         *     Solo superadmin.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "5to B",
                     *       "year": 2025,
                     *       "section": "B",
                     *       "teacherId": "usr_TEACH1",
                     *       "descriptionHeading": "Quinto año sección B — 2025"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Curso creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": "course_5B_2025",
                         *       "name": "5to B",
                         *       "classroomCourseId": "123456789",
                         *       "enrollmentCode": "abc1xyz",
                         *       "createdAt": "2025-03-01T00:00:00Z"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{id}/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Agregar alumno a un curso
         * @description Llama a `courses.students.create` en Google Classroom.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example usr_0ZLUQ */
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "studentId": "usr_0ZLUQ"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Alumno agregado al curso */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "courseId": "course_5B_2025",
                         *       "studentId": "usr_0ZLUQ",
                         *       "classroomEnrolled": true,
                         *       "enrolledAt": "2025-03-01T08:00:00Z"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{id}/students/{studentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remover alumno de un curso */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example usr_0ZLUQ */
                    id: components["parameters"]["id"];
                    studentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alumno removido */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar registros de asistencia */
        get: {
            parameters: {
                query?: {
                    studentId?: string;
                    courseId?: string;
                    /** @example 2025-04-01 */
                    from?: string;
                    /** @example 2025-04-09 */
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Registros de asistencia */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "id": "att_001",
                         *           "studentId": "usr_0ZLUQ",
                         *           "studentName": "Lucas Rodríguez",
                         *           "date": "2025-04-09",
                         *           "status": "presente"
                         *         },
                         *         {
                         *           "id": "att_002",
                         *           "studentId": "usr_0ZLUQ",
                         *           "studentName": "Lucas Rodríguez",
                         *           "date": "2025-04-08",
                         *           "status": "ausente",
                         *           "note": "Avisó con anticipación"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        /**
         * Registrar asistencia
         * @description Registro interno, no se sincroniza con Google Classroom.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "courseId": "course_5B_2025",
                     *       "date": "2025-04-09",
                     *       "records": [
                     *         {
                     *           "studentId": "usr_0ZLUQ",
                     *           "status": "presente"
                     *         },
                     *         {
                     *           "studentId": "usr_0ABCD",
                     *           "status": "ausente",
                     *           "note": "Avisó con anticipación"
                     *         },
                     *         {
                     *           "studentId": "usr_0EFGH",
                     *           "status": "tarde"
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Asistencia registrada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "date": "2025-04-09",
                         *       "courseId": "course_5B_2025",
                         *       "savedCount": 3
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attendance/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Corregir un registro de asistencia */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example usr_0ZLUQ */
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "status": "tarde",
                     *       "note": "Llegó 15 minutos tarde"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Registro actualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/attendance/summary/{studentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resumen de asistencia del alumno */
        get: {
            parameters: {
                query?: {
                    /** @example 2025 */
                    year?: number;
                };
                header?: never;
                path: {
                    studentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Resumen porcentual */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "studentId": "usr_0ZLUQ",
                         *       "studentName": "Lucas Rodríguez",
                         *       "year": 2025,
                         *       "totalDays": 60,
                         *       "presentDays": 57,
                         *       "absentDays": 2,
                         *       "lateDays": 1,
                         *       "percentage": 95,
                         *       "byMonth": [
                         *         {
                         *           "month": "2025-03",
                         *           "present": 20,
                         *           "absent": 1,
                         *           "late": 0
                         *         },
                         *         {
                         *           "month": "2025-04",
                         *           "present": 7,
                         *           "absent": 1,
                         *           "late": 1
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar hilos del usuario autenticado */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Hilos de conversación */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "id": "thread_001",
                         *           "participants": [
                         *             {
                         *               "id": "usr_0ZLUQ_parent",
                         *               "name": "Carlos Rodríguez",
                         *               "role": "padre"
                         *             },
                         *             {
                         *               "id": "usr_TEACH1",
                         *               "name": "María Pérez",
                         *               "role": "docente"
                         *             }
                         *           ],
                         *           "subject": "Consulta sobre examen del martes",
                         *           "lastMessage": "Hola, quería consultar...",
                         *           "lastMessageAt": "2025-04-09T10:30:00Z",
                         *           "unreadCount": 2
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        /** Iniciar nuevo hilo */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "recipientId": "usr_TEACH1",
                     *       "subject": "Consulta sobre examen del martes",
                     *       "message": "Hola María, quería consultar si el examen cubre toda la unidad 3."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Hilo creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": "thread_001",
                         *       "createdAt": "2025-04-09T10:30:00Z"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/threads/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Mensajes de un hilo */
        get: {
            parameters: {
                query?: {
                    page?: number;
                };
                header?: never;
                path: {
                    /** @example usr_0ZLUQ */
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Mensajes paginados */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "thread": {
                         *         "id": "thread_001",
                         *         "subject": "Consulta sobre examen del martes"
                         *       },
                         *       "messages": [
                         *         {
                         *           "id": "msg_001",
                         *           "senderId": "usr_0ZLUQ_parent",
                         *           "senderName": "Carlos Rodríguez",
                         *           "senderRole": "padre",
                         *           "body": "Hola María, quería consultar si el examen cubre toda la unidad 3.",
                         *           "sentAt": "2025-04-09T10:30:00Z",
                         *           "read": true
                         *         },
                         *         {
                         *           "id": "msg_002",
                         *           "senderId": "usr_TEACH1",
                         *           "senderName": "María Pérez",
                         *           "senderRole": "docente",
                         *           "body": "Hola Carlos! Sí, el examen abarca unidad 3 completa. Saludos.",
                         *           "sentAt": "2025-04-09T11:00:00Z",
                         *           "read": false
                         *         }
                         *       ],
                         *       "pagination": {
                         *         "page": 1,
                         *         "total": 2
                         *       }
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        /**
         * Enviar mensaje en un hilo
         * @description Persiste el mensaje y dispara una notificación por email al padre
         *     (si el destinatario es padre, ya que su cuenta no es de Workspace).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example usr_0ZLUQ */
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "body": "Hola Carlos! Sí, el examen abarca unidad 3 completa. Saludos."
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Mensaje enviado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": "msg_002",
                         *       "sentAt": "2025-04-09T11:00:00Z",
                         *       "emailNotificationSent": true
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/announcements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar anuncios
         * @description Solo devuelve anuncios cuya ventana de publicación está activa para el rol del usuario.
         */
        get: {
            parameters: {
                query?: {
                    courseId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Anuncios visibles */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "id": "ann_087",
                         *           "title": "Recordatorio: acto del viernes",
                         *           "body": "Se recuerda que el viernes habrá acto escolar a las 10hs.",
                         *           "publishedAt": "2025-04-08T18:00:00Z",
                         *           "author": "María Pérez"
                         *         },
                         *         {
                         *           "id": "ann_086",
                         *           "title": "Cambio de horario Educación Física",
                         *           "body": "Esta semana Ed. Física pasa al miércoles 4ta hora.",
                         *           "publishedAt": "2025-04-07T08:00:00Z",
                         *           "author": "Roberto García"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        /**
         * Publicar anuncio, nota o sanción
         * @description Permite controlar la ventana horaria en la que los destinatarios pueden ver el anuncio.
         *     Útil para retrasar la publicación de notas o sanciones hasta un horario apropiado.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "title": "Calificaciones examen unidad 3",
                     *       "body": "Se publicaron las notas del examen de Fracciones. Promedio: 7.8",
                     *       "courseId": "course_5B_2025",
                     *       "audience": [
                     *         "alumnos",
                     *         "padres"
                     *       ],
                     *       "publishAt": "2025-04-10T18:00:00Z",
                     *       "visibleUntil": "2025-04-17T23:59:00Z"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Anuncio creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": "ann_088",
                         *       "status": "programado",
                         *       "publishAt": "2025-04-10T18:00:00Z"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/messages/announcements/{id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Configurar horario de visibilidad de un anuncio */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example usr_0ZLUQ */
                    id: components["parameters"]["id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "publishAt": "2025-04-11T18:00:00Z",
                     *       "visibleUntil": "2025-04-18T23:59:00Z"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Horario actualizado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/classroom/courses/{courseId}/work": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar tareas y exámenes
         * @description Llama a Google Classroom `courseWork.list`. Los ítems cuyo título comienza
         *     con `[EXAMEN]` se marcan con `type: "exam"`, el resto como `type: "task"`.
         */
        get: {
            parameters: {
                query?: {
                    /** @example all */
                    type?: "task" | "exam" | "all";
                };
                header?: never;
                path: {
                    /** @example course_5B_2025 */
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Trabajos del curso */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "id": "cw_111",
                         *           "title": "[EXAMEN] Fracciones - Matemática",
                         *           "type": "exam",
                         *           "dueDate": "2025-04-15T08:00:00Z",
                         *           "maxPoints": 10,
                         *           "state": "PUBLISHED"
                         *         },
                         *         {
                         *           "id": "cw_222",
                         *           "title": "Ejercicios de redacción - Lengua",
                         *           "type": "task",
                         *           "dueDate": "2025-04-12T23:59:00Z",
                         *           "maxPoints": 10,
                         *           "state": "PUBLISHED"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        /**
         * Crear tarea o examen en Classroom
         * @description Llama a `courseWork.create` de Google Classroom API.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "title": "[EXAMEN] Números romanos - Historia",
                     *       "description": "Estudiar del capítulo 4 al 7.",
                     *       "dueDate": "2025-04-20",
                     *       "dueTime": "08:00",
                     *       "maxPoints": 10,
                     *       "type": "exam"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Trabajo creado en Classroom */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "classroomWorkId": "444555666",
                         *       "title": "[EXAMEN] Números romanos - Historia",
                         *       "createdAt": "2025-04-09T12:00:00Z"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classroom/courses/{courseId}/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener calificaciones del curso
         * @description Llama a `studentSubmissions.list` para traer notas de todos los alumnos.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Filtrar por tarea/examen específico */
                    workId?: string;
                };
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Calificaciones */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "courseId": "course_5B_2025",
                         *       "data": [
                         *         {
                         *           "studentId": "usr_0ZLUQ",
                         *           "studentName": "Lucas Rodríguez",
                         *           "workId": "cw_111",
                         *           "workTitle": "[EXAMEN] Fracciones",
                         *           "grade": 8.5,
                         *           "maxPoints": 10,
                         *           "state": "TURNED_IN",
                         *           "gradedAt": "2025-04-16T10:00:00Z"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        /**
         * Subir calificaciones a Classroom
         * @description Llama a `studentSubmissions.patch` con `assignedGrade` para cada alumno.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "workId": "cw_111",
                     *       "grades": [
                     *         {
                     *           "studentId": "usr_0ZLUQ",
                     *           "grade": 8.5
                     *         },
                     *         {
                     *           "studentId": "usr_0ABCD",
                     *           "grade": 7
                     *         },
                     *         {
                     *           "studentId": "usr_0EFGH",
                     *           "grade": 9.5
                     *         }
                     *       ]
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Calificaciones subidas */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "updatedCount": 3,
                         *       "failedCount": 0
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classroom/ai-query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Asistente IA — consulta en lenguaje natural
         * @description El asistente consulta Google Classroom (notas, tareas, horarios) en nombre
         *     del usuario autenticado y responde en lenguaje natural.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "query": "¿Cuándo es el próximo examen de Matemática y qué temas entran?"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Respuesta del asistente */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "answer": "El próximo examen de Matemática es el martes 15 de abril. Según la descripción en Classroom, abarca Fracciones y Decimales (unidad 3 completa).",
                         *       "sources": [
                         *         {
                         *           "type": "classroom_work",
                         *           "id": "cw_111",
                         *           "title": "[EXAMEN] Fracciones - Matemática",
                         *           "dueDate": "2025-04-15T08:00:00Z"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspace/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crear cuenta institucional
         * @description Llama a `POST /admin/directory/v1/users` de Google Workspace.
         *     Se ejecuta automáticamente desde `/admissions/prospects/:id/enroll`
         *     pero también puede llamarse manualmente para docentes.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "userId": "usr_0ZLUQ",
                     *       "firstName": "Lucas",
                     *       "lastName": "Rodríguez",
                     *       "institutionalEmail": "lucas.rodriguez@colegio.edu.ar",
                     *       "orgUnitPath": "/Alumnos/Primaria/5to",
                     *       "role": "alumno"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Cuenta creada en Google Workspace */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "googleAccountId": "108765432109876543210",
                         *       "institutionalEmail": "lucas.rodriguez@colegio.edu.ar",
                         *       "orgUnitPath": "/Alumnos/Primaria/5to",
                         *       "createdAt": "2025-04-09T08:00:00Z"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspace/users/{googleId}/ou": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Mover usuario a otra unidad organizativa */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example 108765432109876543210 */
                    googleId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "orgUnitPath": "/Alumnos/Primaria/6to"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description OU actualizada */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        trace?: never;
    };
    "/workspace/users/{googleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Suspender cuenta al dar de baja */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    googleId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cuenta suspendida en Google Workspace */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workspace/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crear grupo de Google
         * @description Crea un grupo de Google Workspace (por curso o rol).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "name": "5to B 2025",
                     *       "email": "5tob-2025@colegio.edu.ar",
                     *       "description": "Grupo del curso 5to B año 2025",
                     *       "members": [
                     *         "lucas.rodriguez@colegio.edu.ar",
                     *         "valentina.lopez@colegio.edu.ar"
                     *       ]
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Grupo creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "googleGroupId": "grp_5B_2025",
                         *       "email": "5tob-2025@colegio.edu.ar",
                         *       "memberCount": 2
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/student": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard del alumno
         * @description Vista personal con materias, tareas, exámenes y asistencia.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dashboard del alumno autenticado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "student": {
                         *         "id": "usr_0ZLUQ",
                         *         "displayName": "Lucas Rodríguez",
                         *         "courseName": "5to B"
                         *       },
                         *       "attendance": {
                         *         "percentage": 95,
                         *         "absentDays": 3
                         *       },
                         *       "upcomingWork": [
                         *         {
                         *           "title": "[EXAMEN] Fracciones",
                         *           "type": "exam",
                         *           "dueDate": "2025-04-15T08:00:00Z",
                         *           "subject": "Matemática"
                         *         }
                         *       ],
                         *       "recentGrades": [
                         *         {
                         *           "subject": "Matemática",
                         *           "grade": 8.5,
                         *           "maxGrade": 10
                         *         }
                         *       ],
                         *       "reminders": [
                         *         "Examen de Matemática en 6 días",
                         *         "Tarea de Lengua vence mañana"
                         *       ]
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/teacher": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard del docente
         * @description Cursos a cargo, alumnos, calificaciones y calendario desde Google Classroom.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dashboard del docente autenticado */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "teacher": {
                         *         "id": "usr_TEACH1",
                         *         "displayName": "María Pérez"
                         *       },
                         *       "courses": [
                         *         {
                         *           "id": "course_5B_2025",
                         *           "name": "5to B",
                         *           "studentCount": 28,
                         *           "pendingGrades": 5,
                         *           "upcomingWork": [
                         *             {
                         *               "title": "[EXAMEN] Fracciones",
                         *               "dueDate": "2025-04-15T08:00:00Z"
                         *             }
                         *           ]
                         *         }
                         *       ],
                         *       "unreadMessages": 3,
                         *       "calendarToday": [
                         *         {
                         *           "time": "08:00",
                         *           "subject": "Matemática 5to B"
                         *         },
                         *         {
                         *           "time": "10:00",
                         *           "subject": "Matemática 6to A"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard/director": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard del director
         * @description Indicadores globales del colegio. Consume cursos y calificaciones de Google Classroom
         *     y asistencia del sistema interno.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Dashboard del director */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "school": {
                         *         "totalStudents": 320,
                         *         "totalTeachers": 24,
                         *         "totalCourses": 12
                         *       },
                         *       "attendance": {
                         *         "todayPercentage": 93.4,
                         *         "weekAverage": 94.1
                         *       },
                         *       "grades": {
                         *         "schoolAverage": 7.6,
                         *         "bySubject": [
                         *           {
                         *             "subject": "Matemática",
                         *             "average": 7.2
                         *           },
                         *           {
                         *             "subject": "Lengua",
                         *             "average": 8.1
                         *           },
                         *           {
                         *             "subject": "Ciencias Naturales",
                         *             "average": 7.9
                         *           }
                         *         ]
                         *       },
                         *       "pendingAdmissions": 8,
                         *       "recentActivity": [
                         *         {
                         *           "type": "enrollment",
                         *           "description": "Lucas Rodríguez dado de alta en 5to B",
                         *           "at": "2025-04-09T08:00:00Z"
                         *         },
                         *         {
                         *           "type": "announcement",
                         *           "description": "María Pérez publicó notas de examen en 5to B",
                         *           "at": "2025-04-08T18:00:00Z"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        AuthTokens: {
            accessToken?: string;
            refreshToken?: string;
            user?: {
                id?: string;
                email?: string;
                /** @enum {string} */
                role?: "superadmin" | "director" | "docente" | "alumno" | "padre";
                displayName?: string;
            };
        };
        ProspectCreate: {
            studentName: string;
            /** Format: date */
            birthDate: string;
            gradeApplying: string;
            parentName?: string;
            /** Format: email */
            parentEmail: string;
            parentPhone?: string;
            notes?: string;
        };
    };
    responses: {
        /** @description Token inválido o ausente */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "UNAUTHORIZED",
                 *       "message": "Token JWT inválido o expirado"
                 *     }
                 */
                "application/json": unknown;
            };
        };
        /** @description Recurso no encontrado */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "NOT_FOUND",
                 *       "message": "El recurso solicitado no existe"
                 *     }
                 */
                "application/json": unknown;
            };
        };
        /** @description Error de validación */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "VALIDATION_ERROR",
                 *       "fields": [
                 *         {
                 *           "field": "parentEmail",
                 *           "message": "Formato de email inválido"
                 *         },
                 *         {
                 *           "field": "birthDate",
                 *           "message": "La fecha no puede ser futura"
                 *         }
                 *       ]
                 *     }
                 */
                "application/json": unknown;
            };
        };
    };
    parameters: {
        /** @example usr_0ZLUQ */
        id: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
